config/routes.rb
Echotalk::Application.routes.draw do
  get "test/jsq"

  root :to => 'static#home'
  get "static/home"

  get "static/portfolio"

  get "static/about"

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def home
  end

  def portfolio
  end

  def about
  end
end

app/controllers/test_controller.rb
class TestController < ApplicationController
  def jsq
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/test_helper.rb
module TestHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
      <head>
        <div class="picture"></div>
        <title>About Me - peterkona.com</title>
        <meta name="description" content="I'm designer and developer this page is all about me but doesn't need to be.
        Contact me and let's work together ikona23@gmail.com">
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
        <%= stylesheet_link_tag 'application', media:'all', 'data-turbolinks-track' => true %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

        <link href='http://fonts.googleapis.com/css?family=Lato-Regular:300,400,700' rel='stylesheet' type='text/css'>

        <%= csrf_meta_tags %>
      </head>
<body>
<header class = "fixed">
  <div class="navbar navbar-fixed-top navbar-inverse" role="navigation">
    <div class="navbar-inner">
      <div class="container">
        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>
        <a class="brand" href="">Peter Kona</a>
        <div class="nav-collapse text-center">
          <ul class="nav">
            <li class="divider"></li>
            <li class=""<%= 'active' if current_page?(root_path) %>"><%= link_to "Home", root_path %></li>
            <li class=""><%= link_to "Porfolio", static_portfolio_path %></li>
            <li class=""><%= link_to "About me", static_about_path%></li>
          </ul>
        </div><!-- /.nav-collapse -->
      </div><!-- /.container -->
    </div><!-- /.navbar-inner -->
  </div><!-- /.navbar -->
</header>
    <div class="container">
  <%= yield %>
    </div>
<div class="footer">
  <div class="inside">
    <a href="http://peterkona.com">Peter Kona</a>
  </div>
</div>

    <script src="//use.typekit.net/tfi4mim.js"></script>
    <script>try{Typekit.load();}catch(e){}</script>
    <script type='text/javascript' src="/assets/application.js"></script>
    <script src='https://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js'></script>
    <script src="/assets/bootstrap.min.js"></script>
    <script type='text/javascript' src="/assets/bootbox.js"></script>
    <script type='text/javascript' src="/assets/jquery.quicksand.js"></script>
    <script type='text/javascript' src="/assets/jquery.js"></script>
    <script type='text/javascript' src="/assets/init.js" ></script>
</body>
</html>
<!--rip cert, rip jozko, rip janko, rip dodo-->